/obj/item/reagent_containers/proc/caustic_attackby(obj/item/I, mob/living/user, params)
	if(istype(I,/obj/item/compost) || istype(I, /obj/item/natural/poo))
		if(!reagents.has_reagent(/datum/reagent/water, 10))
			to_chat(user, span_warning("Not enough water."))
			return
		to_chat(user, span_warning("You begin adding the [I.name] to the water..."))
		if(do_after(user,get_farming_do_time(user,2 SECONDS), target = src))
			apply_farming_fatigue(user, 1)
			add_sleep_experience(user, /datum/skill/labor/farming, user.STAINT * 0.5)
			reagents.remove_reagent(/datum/reagent/water, 10)
			reagents.add_reagent(/datum/reagent/liquid_fertilizer,10)
			to_chat(user,span_notice("You mixed together a sludge of fertilizer. It's what plants crave."))
			qdel(I)
	if(istype(I,/obj/item/fertilizer))
		if(!reagents.has_reagent(/datum/reagent/water, 10))
			to_chat(user, span_warning("Not enough water."))
			return
		to_chat(user, span_warning("You begin adding the [I.name] to the water..."))
		if(do_after(user,get_farming_do_time(user,2 SECONDS), target = src))
			apply_farming_fatigue(user, 2)
			add_sleep_experience(user, /datum/skill/labor/farming, user.STAINT * 0.5)
			reagents.remove_reagent(/datum/reagent/water, 10)
			reagents.add_reagent(/datum/reagent/liquid_fertilizer/premium,10)
			to_chat(user,span_notice("You mixed together a sludge of rich fertilizer. It's what plants REALLY crave."))
			qdel(I)
